steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -lc
      - docker pull ${_CUSTOMER_IMAGE} || true
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --cache-from
      - ${_CUSTOMER_IMAGE}
      - --build-arg
      - BUILDKIT_INLINE_CACHE=1
      - -f
      - customer-app.Dockerfile
      - -t
      - ${_CUSTOMER_IMAGE}
      - .
images:
  - ${_CUSTOMER_IMAGE}
