#!/usr/bin/env python3
"""Restore and fix local-policy.json (rewrites from scratch)."""
import json
from pathlib import Path

F = Path(__file__).resolve().parent.parent / "config/policy/local-policy.json"

d = {
  "patterns": {
    "harassment": [
      "\\bidiot\\b",
      "you are an idiot",
      "\\bstupid\\b",
      "\\bdumb\\b",
      "\\bmoron\\b",
      "stupid\\s+moron",
      "shut\\s+up",
      "fuck\\s*you",
      "f\\*+k\\s*you",
      "fucking\\s+useless",
      "you are useless",
      "\\buseless\\b",
      "\\bworthless\\b",
      "\\bpathetic\\b",
      "\\bloser\\b",
      "\\bincompetent\\b",
      "\\bdisgusting\\b",
      "\\bdisgrace\\b",
      "brain.?dead",
      "what the hell is wrong with you",
      "what.*wrong with you",
      "are you (stupid|kidding|serious|dumb)",
      "worst (company|service|support|agent|product) (ever|i.ve ever)",
      "absolute (trash|garbage|joke|disgrace)",
      "complete (idiot|moron|failure|mess)",
      "total (garbage|trash|waste|joke)",
      "shit\\s*(product|service|support|company|job)",
      "\\bshit\\b",
      "you (people|guys|staff|team|employees) are (useless|incompetent|idiots|morons)",
      "can.?t believe how (dumb|stupid|useless|incompetent)",
      "never (seen|dealt with) such (terrible|awful|pathetic|horrible)",
      "horrible (service|support|job|work)",
      "고객을 뭐로 아는",
      "바보",
      "멍청",
      "한심",
      "형편없",
      "닥치[고어야]?",
      "꺼져",
      "미치겠[다]?|미쳐\\s*(버리|가고|죽겠)",
      "쓸모없",
      "무릎\\s*꿇고\\s*빌어",
      "무릎\\s*꿇어",
      "빌어라",
      "욕[을]?\\s*하",
      "개새|씨발|병신|개새끼|좆같|지랄|ㅅㅂ|ㅂㅅ|ㄱㅅ",
      "미친\\s*(놈|년|새끼|거|짓)",
      "돌았어|정신\\s*나갔",
      "짜증\\s*나(네|요|죽겠|서|는)?",
      "열\\s*받아|열\\s*받네",
      "재수\\s*없",
      "진짜\\s*짜증",
      "이게\\s*(뭐야|뭡니까|서비스야)",
      "이딴\\s*(서비스|것|게|짓|회사)",
      "이런\\s*회사",
      "이\\s*멍청한",
      "이\\s*한심한",
      "도대체\\s*뭐하는",
      "칠칠치\\s*못한",
      "어디서\\s*굴러먹다",
      "그따위",
      "엉터리"
    ],
    "harassmentCritical": [
      "fuck\\s*you",
      "f\\*+k\\s*you",
      "fucking\\s+useless",
      "you are an idiot",
      "stupid\\s+moron",
      "\\bworthless\\b",
      "brain.?dead",
      "absolute (trash|garbage|joke)",
      "complete (idiot|moron)",
      "you (people|guys|staff|team) are (useless|incompetent|idiots|morons)",
      "병신아?",
      "씨발",
      "개새끼",
      "좆같",
      "지랄",
      "ㅅㅂ|ㅂㅅ|ㄱㅅ",
      "미친\\s*(놈|년|새끼)",
      "무릎\\s*꿇고\\s*빌어",
      "무릎\\s*꿇어",
      "빌어라"
    ],
    "threat": [
      "i will (hurt|harm|attack|come for|get)",
      "i will kill",
      "i[' ]?ll kill",
      "kill\\s*you",
      "\\bthreaten\\b",
      "i will find you",
      "watch your back",
      "pay for this",
      "\\bretaliate\\b",
      "destroy your (company|business|reputation|career)",
      "ruin your (company|business|reputation|life|career)",
      "make (you|your company|your business) pay",
      "you([ ']ll|[ '][a-z]+[ ']ll)? (regret|be sorry|suffer)",
      "you will (regret|be sorry|suffer|pay)",
      "i know where (you|your office|your company)",
      "i[' ]?ll (sue|report|expose|destroy|ruin|come)",
      "take (legal action|you to court|this to court)",
      "go to (the media|court|authorities|lawyers?)",
      "get you (fired|arrested|sued)",
      "your (lawyer|attorney) will hear",
      "i[' ]?ll come (to|for) (your|the) (office|store|address)",
      "i[' ]?ll be there",
      "you[' ]?d better",
      "this (isn[' ]?t|is not) over",
      "just (wait|you wait)",
      "swear (to god|i[' ]?ll)",
      "죽여버리",
      "죽어버[려리]",
      "죽을래",
      "죽고\\s*싶",
      "너.*죽",
      "죽여줄",
      "가만\\s*(안\\s*둘|안\\s*둬|두지\\s*않)",
      "해치겠|해칠\\s*거|해치울",
      "찾아가서|찾아갈\\s*거|찾아가겠",
      "보복하겠|보복할\\s*거",
      "고소하겠|고소할\\s*거|고소\\s*할",
      "신고하겠|신고할\\s*거|경찰에\\s*신고",
      "두고\\s*봐|두고\\s*볼",
      "후회하게\\s*(해줄|만들|될)",
      "망하게\\s*해줄|망해[버]?[려리]",
      "각오해[라]?",
      "끝장\\s*(내|날\\s*거|내줄)",
      "가만\\s*안\\s*놓을",
      "어디\\s*(있는지|사는지)\\s*(다\\s*)?알아",
      "퍼뜨리겠|폭로하겠|폭로할|까발리겠",
      "언론에\\s*알리겠|기자한테\\s*알리"
    ],
    "threatCritical": [
      "i will kill",
      "i[' ]?ll kill",
      "kill\\s*you",
      "i will (hurt|harm|attack)",
      "i will find you",
      "i know where (you|your office|your company)",
      "watch your back",
      "make (you|your company) pay",
      "destroy your (company|business|reputation|career)",
      "ruin your (company|business|reputation|life|career)",
      "i[' ]?ll come (to|for) (your|the) (office|store|address)",
      "i[' ]?ll.{0,10}(get you|make you pay)",
      "swear.{0,10}(i.?ll|to god)",
      "just (wait|you wait)",
      "this (isn.?t|is not) over",
      "죽여버리",
      "죽어버[려리]",
      "죽을래",
      "너.*죽",
      "해치겠|해칠\\s*거|해치울",
      "찾아가서|찾아갈\\s*거",
      "보복하겠|보복할\\s*거",
      "끝장\\s*(내|날\\s*거|내줄)",
      "어디\\s*(있는지|사는지)\\s*(다\\s*)?알아",
      "두고\\s*봐|두고\\s*볼",
      "후회하게\\s*(해줄|만들|될)",
      "망하게\\s*해줄|망해[버]?[려리]",
      "퍼뜨리겠|폭로하겠|폭로할|까발리겠",
      "가만\\s*(안\\s*둘|안\\s*둬|두지\\s*않)"
    ],
    "sexual": [
      "(?<![a-z])sex(?![ual\\s]*(abuse|crime|offend|assault|harass|traffick))",
      "have\\s+sex\\s+with",
      "\\bnude\\b",
      "nude\\s*(photo|pic|picture|image|selfie|body)",
      "(photo|pic|picture|image|selfie)\\s*nude",
      "your\\s+body",
      "your\\s+.{1,15}\\s*body",
      "sleep\\s+with\\s+me",
      "\\bsexy\\b",
      "\\bsexual\\b",
      "show me\\s+(your\\s+)?(nude|naked|body|chest|ass|boob)",
      "send\\s+(me\\s+)?(nude|naked|naughty|dirty|explicit)",
      "want\\s+to\\s+see\\s+you\\s+(naked|nude|undressed)",
      "i\\s+want\\s+to\\s+f(uck|\\*+k?)\\s+(you|her|him)",
      "wanna\\s+f(uck|\\*+k?)|want\\s+to\\s+f(uck|\\*+k?)",
      "let.?s\\s+(have\\s+sex|hook\\s+up|do\\s+it|sleep\\s+together)",
      "you[''`]re\\s+(so\\s+)?(hot|sexy|gorgeous)",
      "send\\s+nudes",
      "dirty\\s+talk",
      "naughty\\s+(girl|boy|photo|pic|video)",
      "are\\s+you\\s+single",
      "wanna\\s+(date|meet|hook\\s+up)",
      "come\\s+home\\s+with\\s+me",
      "i[' ]?ll\\s+make\\s+(you|it)\\s+(feel\\s+good|worth\\s+it)",
      "섹시",
      "누드",
      "야한",
      "야동",
      "야사",
      "야설",
      "성희롱",
      "성적",
      "몸매",
      "벗[어]",
      "옷\\s*벗",
      "벗고\\s*(셀피|사진)",
      "셀피.*(찍어|보내)",
      "벗은\\s*(셀피|사진)",
      "누드.*보내|보내.*누드",
      "야한.*보내|보내.*야한",
      "야한.*사진|사진.*야한",
      "수위\\s*(높은|있는|높여)",
      "같이\\s*자|나랑\\s*자[지]?|자지\\s*(않을래|볼래|않을게)",
      "사귀[어자고]",
      "사귈래",
      "연락처\\s*(줘|주세요|알려)",
      "카카오\\s*(알려|줘|주세요)",
      "번호\\s*(줘|주세요|알려)",
      "만나\\s*(줘|자|볼래|주세요)",
      "직접\\s*만나",
      "화상\\s*(통화|연결|해줘|할래)",
      "나\\s*(좋아|좋아해)?\\s*사진\\s*(보내|줘)"
    ]
  },
  "weights": {
    "keyword": {
      "harassment": 2.4,
      "threat": 1.2,
      "sexual": 1.95
    },
    "combine": {
      "keyword": 0.82,
      "semantic": 0.18
    },
    "harassmentCriticalBoost": 0.18,
    "threatCriticalBoost": 0.45,
    "repeatedAbuseBoost": 0.15
  },
  "semantic": {
    "power": 0.85,
    "positiveOnly": True
  },
  "repetition": {
    "minTokenLength": 3,
    "minCountPerToken": 3
  }
}

F.write_text(json.dumps(d, ensure_ascii=False, indent=2))
print("Restored and patched successfully.")
print(f"  harassment patterns: {len(d['patterns']['harassment'])}")
print(f"  threat patterns:     {len(d['patterns']['threat'])}")
print(f"  sexual patterns:     {len(d['patterns']['sexual'])}")
print(f"  threatCritical:      {len(d['patterns']['threatCritical'])}")
print(f"  sexual weight:       {d['weights']['keyword']['sexual']}")
print(f"  threatCriticalBoost: {d['weights']['threatCriticalBoost']}")

